### ISSUE TITLE
Feature request: Add a new state, FULL_VISIBLE

### ISSUE THREAD

**Issue by davesnx** [civiccc/react-waypoint#292]
Hey @brigade-gerrit,

I'm working on a UI that I needed to make a difference between something that has been passed the Viewport by 1 pixel and something that is full on the viewport.

Right now, react-waypoint triggers `INSIDE` as soon as the element is inside the viewport, I would love to add a `FULL_VISIBLE` that is being triggered when the element is completely inside the viewport.

It's actually here: https://github.com/brigade/react-waypoint/blob/master/src/getCurrentPosition.js#L30

I don't want to rely on any fixed offset neither since I could not ensure that this element is the same size all the time.

Does it make sense? Do I have a way to make that work?

**Comment by trotzig** [comment]
I would look at https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API for that. 

The workaround right now with react-waypoint is to add two waypoints; one at the top and one at the bottom. When both are inside, the whole element is inside.

**Comment by lencioni** [comment]
Maybe we should add something to the top of the readme directing folks toward intersection observer?

**Comment by davesnx** [comment]
Two wayponints works perfect. Thanks @trotzig
