### ISSUE TITLE
Demo is down because Brigade was acquired

### ISSUE THREAD

**Issue by sibnerian** [civiccc/react-waypoint#307]
The link to the demo no longer has any React related content. Instead, it shows a message related to Brigade's acquisition: 

> After two election cycles and nearly five years of building tools to help voters to play a fuller role in their democracy, we are excited to announce that Brigade is joining Countable. We can’t imagine a better home for Brigade’s community and technology. Countable shares our philosophy for deeper, more impactful civic engagement enabled by technology.

**Comment by z3usy** [comment]
@sibnerian Thanks for the heads up! I've removed the link for now and if anyone gets the chance to throw up another demo page we'll re-link it. Cheers!
