### ISSUE TITLE
[Question] What's the differences with react-intersection-observer?

### ISSUE THREAD

**Issue by kud** [civiccc/react-waypoint#318]
https://github.com/thebuilder/react-intersection-observer

**Comment by lencioni** [comment]
They aim to do roughly the same thing. react-waypoint will use scroll event listeners and react-intersection-observer will use IntersectionObserver. For performance reasons, I'd highly recommend using IntersecionObserver wherever possible.

**Comment by kud** [comment]
Yeah me too, that's why I asked this.

Thank you very much!
