### ISSUE TITLE
Demo page is missing

### ISSUE THREAD

**Issue by DanLipsitt** [civiccc/react-waypoint#320]
http://brigade.github.io/react-waypoint/ redirects to https://www.countable.us/, which means the demo isn't available. This looks like a DNS-level issue. It's unclear what if anything has changed since #307 was closed. Can it be hosted at civiccc.github.io or something?

**Comment by DanLipsitt** [comment]
I see now that it is indeed at http://civiccc.github.io/react-waypoint/, so the README just needs to point there.

**Comment by lencioni** [comment]
Thanks!
