### ISSUE TITLE
infinitive scroll

### ISSUE THREAD

**Issue by sm2017** [civiccc/react-waypoint#329]
I implemented an infinitive scroll with `react-waypoint` , ?I put `waypoint` at the bottom of my list, When list reaches to end I load more content
How can I fire my fetching callback when we have 200px scrolling offset from bottom?

**Comment by trotzig** [comment]
Hi @sm2017! Have a look at the section on offsets and boundaries in the readme. I think it could help you figure this out: https://github.com/civiccc/react-waypoint#offsets-and-boundaries
