### ISSUE TITLE
Waypoint causing gap between fetched element count

### ISSUE THREAD

**Issue by rosman83** [civiccc/react-waypoint#361]
This plugin is working fine but on fetch it leaves a padding like gap between the last fetched items and the next set in a vertical list. This makes lists look really weird and spaced oddly as one element is spaced much more than the others at the waypoint

**Comment by trotzig** [comment]
Hi @rosman83! By default, the waypoint is [rendered as a `<span>` element](https://github.com/civiccc/react-waypoint/blob/223991491ea591788b51ef1f824fd58efc7980e5/src/waypoint.jsx#L303). As long as you keep that element outside of the list, it shouldn't affect styling.
